<a href="https://colab.research.google.com/github/SophieShin/CLA3109_class/blob/main/practice_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [1]:
import tensorflow as tf
print('Tensorflow: ', tf.__version__)
import numpy as np
import matplotlib.pyplot as plt

Tensorflow:  2.8.0


In [2]:
# 0으로 채워진 3x4 tensor 만들기
x = tf.zeros([3, 4], tf.int32)
print(x, '\n')

# 1로 채워진 3x4 tensor 만들기
x = tf.ones([3, 4], tf.int32)
print(x, '\n')

# 상수값으로 채워진 1차원 tensor 만들기
x = tf.constant([1, 2.5, 4.6, 5.75, 9.7])
print(x, '\n')

# 상수값으로 채워진 2x2 tensor 만들기
x = tf.constant((np.arange(16).reshape(4, 4)))
print(x, '\n')

# numpy array를 tensor로 변환하기
x = tf.convert_to_tensor(np.array([1,2,3]))
print(x, '\n')

# tensor를 numpy로 변환하기
x = x.numpy()
print(x)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32) 

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32) 

tf.Tensor([1.   2.5  4.6  5.75 9.7 ], shape=(5,), dtype=float32) 

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]], shape=(4, 4), dtype=int64) 

tf.Tensor([1 2 3], shape=(3,), dtype=int64) 

[1 2 3]


### 연산하기

In [4]:
A = tf.constant([
    [4, 3],
    [1, 1],
], dtype=tf.float32, name='A')

B = tf.constant([
    [3, 5],
    [1, 2],
], dtype=tf.float32, name='B')

In [5]:
print('A + B =', tf.add(A, B))

A + B = tf.Tensor(
[[7. 8.]
 [2. 3.]], shape=(2, 2), dtype=float32)


In [6]:
print('A - B =', tf.subtract(A, B))

A - B = tf.Tensor(
[[ 1. -2.]
 [ 0. -1.]], shape=(2, 2), dtype=float32)


In [7]:
print('A ⨉ B =', tf.matmul(A, B))

A ⨉ B = tf.Tensor(
[[15. 26.]
 [ 4.  7.]], shape=(2, 2), dtype=float32)


In [8]:
print('A * B =', tf.multiply(A, B))

A * B = tf.Tensor(
[[12. 15.]
 [ 1.  2.]], shape=(2, 2), dtype=float32)


In [9]:
print('A² =', tf.square(A))

A² = tf.Tensor(
[[16.  9.]
 [ 1.  1.]], shape=(2, 2), dtype=float32)


In [10]:
print('sum(A) =', tf.reduce_sum(A))

sum(A) = tf.Tensor(9.0, shape=(), dtype=float32)


In [11]:
print('det(A) =', tf.linalg.det(A))

det(A) = tf.Tensor(1.0, shape=(), dtype=float32)


In [12]:
print('inv(A) =', tf.linalg.inv(A))

inv(A) = tf.Tensor(
[[ 1. -3.]
 [-1.  4.]], shape=(2, 2), dtype=float32)


In [13]:
print('A ⨉ inv(A) =', tf.matmul(A, tf.linalg.inv(A)))

A ⨉ inv(A) = tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


### Broadcasting

Broadcasting은 NumPy에서 차용한 개념. 특정 조건에서 더 작은 텐서는 결합된 작업을 실행할 때 더 큰 텐서에 맞게 자동으로 "늘어남".

가장 간단하고 일반적인 경우는 Scalar에 Tensor를 곱하거나 추가하려고 할 때로, Scalar는 다른 인수와 동일한 모양으로 Broadcasting됨.

In [14]:
print('A + 1 = ', tf.add(A, 1))

A + 1 =  tf.Tensor(
[[5. 4.]
 [2. 2.]], shape=(2, 2), dtype=float32)


### Tensor Shape

- **Shape**: The length (number of elements) of each of the axes of a tensor.
- **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
- **Axis** or **Dimension**: A particular dimension of a tensor.
- **Size**: The total number of items in the tensor, the product shape vector.

<img src="https://www.tensorflow.org/guide/images/tensor/shape2.png" align="center" width="400"/>

In [15]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [16]:
print("Type of every element:", rank_4_tensor.dtype)

Type of every element: <dtype: 'float32'>


In [17]:
print("Number of axes:", rank_4_tensor.ndim)

Number of axes: 4


In [19]:
print("Shape of tensor:", rank_4_tensor.shape)

Shape of tensor: (3, 2, 4, 5)


In [20]:
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])

Elements along axis 0 of tensor: 3


In [21]:
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])

Elements along the last axis of tensor: 5


In [22]:
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Total number of elements (3*2*4*5):  120


### Indexing

In [23]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [24]:
print("First:", rank_1_tensor[0].numpy())

First: 0


In [25]:
print("Second:", rank_1_tensor[1].numpy())

Second: 1


In [26]:
print("Last:", rank_1_tensor[-1].numpy())

Last: 34


In [27]:
print("Everything:", rank_1_tensor[:].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]


In [28]:
print("Before 4:", rank_1_tensor[:4].numpy())

Before 4: [0 1 1 2]


In [29]:
print("From 4 to the end:", rank_1_tensor[4:].numpy())

From 4 to the end: [ 3  5  8 13 21 34]


In [30]:
print("From 2, before 7:", rank_1_tensor[2:7].numpy())

From 2, before 7: [1 2 3 5 8]


In [31]:
print("Every other item:", rank_1_tensor[::2].numpy())

Every other item: [ 0  1  3  8 21]


In [32]:
print("Reversed:", rank_1_tensor[::-1].numpy())

Reversed: [34 21 13  8  5  3  2  1  1  0]


### Multi-axis indexing

In [33]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [34]:
print(rank_2_tensor[1, 1].numpy())

4.0


In [35]:
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [36]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [37]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


### Manipulating Shapes

In [38]:
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [39]:
print(x.shape.as_list())

[3, 1]


In [40]:
reshaped = tf.reshape(x, [1, 3])

print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


### More on Tensorflow

[Official API Documentation](https://www.tensorflow.org/tutorials)